services:
  api:
    build: .
    container_name: nequi-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      DB_URL: jdbc:postgresql://database-nequi.col8a4sko28q.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=require
      DB_USER: postgres
      DB_PASSWORD: NequiPrueba23
      JPA_DDL_AUTO: update
